# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Juniper Studio Home
email: jeff@juniperstudio.com
description: > # this means to ignore newlines until "baseurl:"
  Juniper Studio Home brings you one of a kind and contract furniture designs. Jeff W. Petersen has been designing and building furniture for over 20 years. Inspired by Danish Modern, Art Deco, Arts & Crafts, Japanese Design and Shaker Furniture. Based in Spring Hill Kansas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://juniperstudio.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock


sass:
  sass_dir: _sass

plugins:
  - breakpoint
  - susy
  - jekyll-sitemap
  - jekyll-paginate

paginate: 2